#!/bin/bash
###==============================================================================###
#   Create an FIO jobfile for a range of iodepths.
#
#   - For latency tests - NumJobs=1 
#   - This will output a standard csv log for each iodepth
#
###==============================================================================###

# Folders and files
LOG_DIR="$HOME/tests/logs"
JOB_DIR="$HOME/tests/jobs"
JOB_FILE="$JOB_DIR/iodepth_range.ini"

# Configurable Parameters
FILENAME="/dev/nvme0n2"
SIZE="1G"
RUNTIME="1800"
BS="4k"
RW="randrw"
RWMIXREAD="70"
NUMJOBS="1"


# Check if log directory exists - create if it doesn't otherwise keep going
if [[ ! -d "$LOG_DIR" ]]; then
    echo "Creating log directory: $LOG_DIR"
    mkdir -p "$LOG_DIR"
else
    echo "Log directory already exists: $LOG_DIR"
fi

# Check if job file exists
if [[ -f "$JOB_FILE" ]]; then
    read -p "$JOB_FILE already exists. Overwrite? (y/n): " confirm
    if [[ "$confirm" != "y" ]]; then
        echo "Aborted."
        exit 1
    fi
fi


###--- Generate the job file
cat << EOF > "$JOB_FILE"
# Generated by script
# Evaluate latency at different iodepths 
[global]
filename=$FILENAME
ioengine=libaio
direct=1
size=$SIZE
runtime=$RUNTIME
time_based=1
bs=$BS
rw=$RW
rwmixread=$RWMIXREAD
numjobs=$NUMJOBS
group_reporting=1
log_avg_msec=1000
EOF

# Generate individual test sections
for QD in 1 2 4 8 16 32 64; do
cat << EOF >> "$JOB_FILE"

[lat_test_qd_$QD]
iodepth=$QD
write_lat_log=$LOG_DIR/ssd_lat_test_lat_qd_$QD
EOF
done

echo "FIO job file generated: $JOB_FILE"

# Optionally run the test
# Uncomment the next line to execute the job file directly
# sudo fio "$JOB_FILE"
# chown -R azureuser:azureuser ./jobs
